/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Document {
  content: Json | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  markdown: string | null;
  title: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface SotesPost {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string | null;
  updated_at: Timestamp | null;
}

export interface DB {
  document: Document;
  sotes_post: SotesPost;
}
